name: CI clang-format

on: [push, pull_request]

jobs:
  clang-format-check:
    name: clang-format-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Git submodule
        run: |
          git submodule sync
          git submodule update --init --recursive

      - name: Install clang-format-14
        run: sudo apt install clang-format-14 -yq

      - name: Check code style
        run: bash formatter.sh --check
